version: "3.7"

services:
  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
      - 443:443
    networks:
      - network
    volumes:
      - /home/django_3_22/nginx.conf:/etc/nginx/nginx.conf # ← 실제 파일이 있는지 확인 필수!
      - static_volume:/data/static
    depends_on:
      - django_container

  django_container:
    image: django_course:v1.0.0
    networks:
      - network
    volumes:
      - static_volume:/home/django_3_22/staticfiles
    environment:
      - DJANGO_SECRET_KEY=super-secret-key
      - POSTGRES_DB=django_db
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=yourpassword123

  postgresdb:
    image: postgres:13.11
    networks:
      - network
    ports:
      - 5432:5432
    volumes:
      - postgres_database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=yourpassword123

networks:
  network:

volumes:
  postgres_database:
  static_volume:
