version: "3.7"

services:
  nginx:
    image: nginx:1.19.5
    ports:
      - "80:80"
      - "443:443"
    networks:
      - network
    volumes:
      - /home/django_3_22/nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/data/static
    depends_on:
      - django_container

  django_container:
    image: django_3_22:v1.0.0
    networks:
      - network
    volumes:
      - static_volume:/home/django_3_22/staticfiles
      - sqlite_volume:/home/django_3_22/db
    environment:
      - DJANGO_SECRET_KEY=super-secret-key
      - DATABASE_NAME=/home/django_3_22/db/db.sqlite3
      - DATABASE_PATH=/home/django_3_22/db

networks:
  network:

volumes:
  static_volume:
  sqlite_volume:
